name: CodeTour watch

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    codetour-watch:
        runs-on: trailheadapps-Ubuntu
        if: github.actor != 'trailheadapps-bot' && github.actor != 'dependabot[bot]'
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v3

            - name: 'Watch CodeTour changes'
              uses: pozil/codetour-watch@v2.0.0

    skip-codetour-watch:
        if: github.actor == 'trailheadapps-bot' || github.actor == 'dependabot[bot]'
        runs-on: trailheadapps-Ubuntu
        steps:
            - name: Noop
              run: |
                  echo "Skipping workflow run for automated PRs."
